

services:
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:/models
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - LLM_HOST=llm-cpu
      - LLM_PORT=8001
      - LOG_LEVEL=INFO
    depends_on:
      - chroma
      - llm-cpu
    networks:
      - stackguide
    profiles:
      - cpu

  # Chroma Vector Database
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8002:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    networks:
      - stackguide

  # vLLM Service for gpt-oss (GPU-accelerated)
  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    ports:
      - "8001:8000"
    volumes:
      - ./models:/models
      - ./data:/data
    environment:
      - MODEL_NAME=gpt-oss-20b
      - MAX_MODEL_LEN=8192
      - GPU_MEMORY_UTILIZATION=0.9
      - ENABLE_GPU=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - stackguide
    profiles:
      - gpu

  # CPU-friendly LLM Service (default)
  llm-cpu:
    build:
      context: .
      dockerfile: Dockerfile.llm-cpu
    ports:
      - "8001:8000"
    volumes:
      - ./models:/models
      - ./data:/data
    environment:
      - MODEL_NAME=llama2-7b-chat
      - MAX_MODEL_LEN=4096
      - ENABLE_GPU=false
    networks:
      - stackguide
    profiles:
      - cpu

  # FastAPI Backend (GPU mode)
  api-gpu:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:/models
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - LLM_HOST=vllm
      - LLM_PORT=8001
      - LOG_LEVEL=INFO
    depends_on:
      - chroma
      - vllm
    networks:
      - stackguide
    profiles:
      - gpu

networks:
  stackguide:
    driver: bridge

volumes:
  chroma_data:
    driver: local
