version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stackguide-postgres
    environment:
      POSTGRES_DB: stackguide
      POSTGRES_USER: stackguide
      POSTGRES_PASSWORD: stackguide_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stackguide"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stackguide-go-backend
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=stackguide
      - DB_USER=stackguide
      - DB_PASSWORD=stackguide_dev
      - DB_SSL_MODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/go.sum
      - /app/go.mod
    command: go run main.go

volumes:
  postgres_data:
